/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Bars: typeof import('./src/components/statistics/Bars.vue')['default']
    Charts: typeof import('./src/components/statistics/Charts.vue')['default']
    ItemCreate: typeof import('./src/components/item/ItemCreate.vue')['default']
    ItemForm: typeof import('./src/components/item/ItemForm.vue')['default']
    ItemList: typeof import('./src/components/item/ItemList.vue')['default']
    ItemSummary: typeof import('./src/components/item/ItemSummary.vue')['default']
    LineChart: typeof import('./src/components/statistics/LineChart.vue')['default']
    PieChart: typeof import('./src/components/statistics/PieChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TagCreate: typeof import('./src/components/tag/TagCreate.vue')['default']
    TagEdit: typeof import('./src/components/tag/TagEdit.vue')['default']
    TagForm: typeof import('./src/components/tag/TagForm.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanDatePicker: typeof import('vant/es')['DatePicker']
    VanDatetimePicker: typeof import('vant/es')['DatetimePicker']
    VanDialog: typeof import('vant/es')['Dialog']
    VanField: typeof import('vant/es')['Field']
    VanOverlay: typeof import('vant/es')['Overlay']
    VanPopup: typeof import('vant/es')['Popup']
    VanRadio: typeof import('vant/es')['Radio']
    VanRadioGroup: typeof import('vant/es')['RadioGroup']
    WelcomeFour: typeof import('./src/components/welcome/WelcomeFour.vue')['default']
    WelcomeLayout: typeof import('./src/components/welcome/WelcomeLayout.vue')['default']
    WelcomeOne: typeof import('./src/components/welcome/WelcomeOne.vue')['default']
    WelcomeThree: typeof import('./src/components/welcome/WelcomeThree.vue')['default']
    WelcomeTwo: typeof import('./src/components/welcome/WelcomeTwo.vue')['default']
  }
}
