/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ItemCreate: typeof import('./src/components/item/ItemCreate.vue')['default']
    ItemList: typeof import('./src/components/item/ItemList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WelcomeFour: typeof import('./src/components/welcome/WelcomeFour.vue')['default']
    WelcomeLayout: typeof import('./src/components/welcome/WelcomeLayout.vue')['default']
    WelcomeOne: typeof import('./src/components/welcome/WelcomeOne.vue')['default']
    WelcomeThree: typeof import('./src/components/welcome/WelcomeThree.vue')['default']
    WelcomeTwo: typeof import('./src/components/welcome/WelcomeTwo.vue')['default']
  }
}
